version: '3.4'

services:

   sistemadetarefasapi:
     image: ${DOCKER_REGISTRY-}sistarefas
     build:
       context: ../SistemaDeTarefas
       dockerfile: ../SistemaDeTarefas/Dockerfile
     ports:
       - "5000:80"
     depends_on:
      - postgres
    
   postgres:
     image: postgres
     restart: always
     environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=SistemaDeTarefas
     ports:
      - "1450:1433"